/**
 * CLI Generate Command Tests
 * Tests TV-CLI-GEN-001, TV-CLI-GEN-002, TV-CLI-DEP-001, TV-CLI-DEP-002,
 * TV-CLI-ERR-001, TV-CLI-ERR-002 from TEST_VECTORS.md
 */

import { describe, it, expect, beforeAll, afterAll, afterEach } from "vitest";
import { execSync } from "node:child_process";
import {
  mkdirSync,
  rmSync,
  writeFileSync,
  existsSync,
  readFileSync,
} from "node:fs";
import { join, resolve } from "node:path";

const CLI_PATH = resolve(__dirname, "../src/cli.ts");
const FIXTURE_DIR = resolve(__dirname, "__cli-test-fixtures__");
const SCHEMA_PATH = join(FIXTURE_DIR, "schema.json");

// Track files created by tests for cleanup
const filesToClean: string[] = [];

function runCli(args: string): { stdout: string; stderr: string; exitCode: number } {
  try {
    const stdout = execSync(`npx tsx ${CLI_PATH} ${args}`, {
      cwd: FIXTURE_DIR,
      encoding: "utf-8",
      env: { ...process.env, NODE_NO_WARNINGS: "1" },
      stdio: ["pipe", "pipe", "pipe"],
    });
    return { stdout, stderr: "", exitCode: 0 };
  } catch (err: any) {
    return {
      stdout: err.stdout ?? "",
      stderr: err.stderr ?? "",
      exitCode: err.status ?? 1,
    };
  }
}

function extractPath(stdout: string, marker: string): string | null {
  const match = stdout.match(new RegExp(`${marker}: (.+)`));
  return match ? match[1].trim() : null;
}

beforeAll(() => {
  if (existsSync(FIXTURE_DIR)) {
    rmSync(FIXTURE_DIR, { recursive: true, force: true });
  }
  mkdirSync(FIXTURE_DIR, { recursive: true });

  const testSchema = {
    resources: [
      {
        name: "todos",
        version: 1,
        fields: [
          { name: "id", type: "string", required: true },
          { name: "text", type: "string", required: true },
          { name: "completed", type: "boolean", required: false, default: false },
        ],
      },
    ],
    relations: [],
  };

  writeFileSync(SCHEMA_PATH, JSON.stringify(testSchema, null, 2));
});

afterEach(() => {
  for (const f of filesToClean) {
    if (existsSync(f)) rmSync(f, { recursive: true, force: true });
  }
  filesToClean.length = 0;
});

afterAll(() => {
  if (existsSync(FIXTURE_DIR)) {
    rmSync(FIXTURE_DIR, { recursive: true, force: true });
  }
});

describe("CLI generate command", () => {
  describe("TV-CLI-GEN-001: Unified generate command - End-to-End", () => {
    it("should generate both schema and types files", () => {
      const outputDir = join(FIXTURE_DIR, "gen-001");
      filesToClean.push(outputDir);

      const result = runCli(
        `generate --adapter drizzle --database postgres --schema ${SCHEMA_PATH} --output ${outputDir}`,
      );

      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("Schema written to:");
      expect(result.stdout).toContain("datafn-schema.drizzle.ts");
      expect(result.stdout).toContain("Types written to:");
      expect(result.stdout).toContain("datafn-types.ts");

      const schemaPath = join(outputDir, "datafn-schema.drizzle.ts");
      const typesPath = join(outputDir, "datafn-types.ts");
      expect(existsSync(schemaPath)).toBe(true);
      expect(existsSync(typesPath)).toBe(true);

      // Verify Drizzle schema content
      const schemaContent = readFileSync(schemaPath, "utf-8");
      expect(schemaContent).toContain("// Generated by @datafn/cli. DO NOT EDIT.");
      expect(schemaContent).toContain("// Database: postgres");
      expect(schemaContent).toContain("pgTable");
      expect(schemaContent).toContain('export const todos = pgTable("todos"');

      // Verify types content
      const typesContent = readFileSync(typesPath, "utf-8");
      expect(typesContent).toContain("export interface Todos");
      expect(typesContent).toContain("export type TypedClient");
    });
  });

  describe("TV-CLI-GEN-002: generate with custom output directory", () => {
    it("should write files to specified output directory", () => {
      const outputDir = join(FIXTURE_DIR, "custom-output");
      filesToClean.push(outputDir);

      const result = runCli(
        `generate --adapter drizzle --database postgres --schema ${SCHEMA_PATH} --output ${outputDir}`,
      );

      expect(result.exitCode).toBe(0);
      expect(existsSync(join(outputDir, "datafn-schema.drizzle.ts"))).toBe(true);
      expect(existsSync(join(outputDir, "datafn-types.ts"))).toBe(true);
    });
  });

  describe("TV-CLI-DEP-001: Deprecated generate-types notice", () => {
    it("should print deprecation notice and exit with code 1", () => {
      const result = runCli("generate-types");

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("'generate-types' has been replaced by 'generate'");
      expect(result.stderr).toContain("Usage: datafn generate --adapter drizzle --database postgres");
    });
  });

  describe("TV-CLI-DEP-002: Deprecated generate-migration notice", () => {
    it("should print deprecation notice and exit with code 1", () => {
      const result = runCli("generate-migration");

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("'generate-migration' has been removed");
      expect(result.stderr).toContain("drizzle-kit generate");
      expect(result.stderr).toContain("drizzle-kit migrate");
    });
  });

  describe("TV-CLI-ERR-001: Missing --adapter flag", () => {
    it("should print error about missing --adapter", () => {
      const result = runCli(
        `generate --database postgres --schema ${SCHEMA_PATH}`,
      );

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("--adapter is required");
      expect(result.stderr).toContain("Supported: drizzle");
    });
  });

  describe("TV-CLI-ERR-002: Missing --database flag", () => {
    it("should print error about missing --database", () => {
      const result = runCli(
        `generate --adapter drizzle --schema ${SCHEMA_PATH}`,
      );

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("--database is required");
      expect(result.stderr).toContain("Supported: postgres, mysql, sqlite");
    });
  });

  describe("Unsupported adapter error", () => {
    it("should print error for unsupported adapter", () => {
      const result = runCli(
        `generate --adapter prisma --database postgres --schema ${SCHEMA_PATH}`,
      );

      expect(result.exitCode).toBe(1);
      expect(result.stderr).toContain("Unsupported adapter: prisma");
      expect(result.stderr).toContain("Currently supported: drizzle");
    });
  });

  describe("Help text", () => {
    it("should show updated help text with generate command", () => {
      const result = runCli("--help");

      expect(result.exitCode).toBe(0);
      expect(result.stdout).toContain("generate");
      expect(result.stdout).toContain("--adapter");
      expect(result.stdout).toContain("--database");
      expect(result.stdout).toContain("Production Workflow");
      expect(result.stdout).not.toContain("generate-migration");
      expect(result.stdout).not.toContain("generate-types");
    });
  });
});
