import { requireScope, type StorageAdapter, type MemoryScope, type MemoryUpdate, type MemoryDelete, type MemoryInsert, type MemoryRelationshipInsert } from '../adapter';
import { Memory, MemoryRelationship } from '../../core/types';
import { memories, memoryRelationships } from './schema';
import { and, eq, sql, isNull, or, arrayContains, inArray } from 'drizzle-orm';
import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

// We assume the DB passed is compatible with PostgresJsDatabase schema
export class PostgresAdapter implements StorageAdapter {
  readonly embeddingDimensions = 1536;
  private db: PostgresJsDatabase<any>;

  constructor(db: PostgresJsDatabase<any>, private readonly dispose?: () => Promise<void>) {
    this.db = db;
  }

  async transaction<T>(operation: (storage: StorageAdapter) => Promise<T>): Promise<T> {
    return this.db.transaction(tx => operation(new PostgresAdapter(tx as unknown as PostgresJsDatabase<any>)));
  }

  async close(): Promise<void> { await this.dispose?.(); }

  async insertMemories(memoryInputs: MemoryInsert[]): Promise<Memory[]> {
    if (memoryInputs.length === 0) return [];

    for (const input of memoryInputs) requireScope(input.tenantId, input.containerTags);
    const now = new Date();
    
    // Map domain model to schema
    const values = memoryInputs.map(m => ({
      // id is autogenerated if not present, but we prefer letting DB generate it or using what's passed
      ...(m.id ? { id: m.id } : {}),
      tenantId: m.tenantId,
      containerTags: [...m.containerTags],
      type: m.type || 'conversational',
      content: m.content || '',
      embedding: m.embedding || null,
      metadata: m.metadata || {},
      isLatest: m.isLatest ?? true,
      createdAt: m.createdAt ? new Date(m.createdAt) : now,
      updatedAt: m.updatedAt ? new Date(m.updatedAt) : now,
    }));

    const result = await this.db.insert(memories)
      .values(values)
      .returning();

    return result.map(this.mapToDomain);
  }

  async insertRelationships(relationships: MemoryRelationshipInsert[]): Promise<MemoryRelationship[]> {
    if (relationships.length === 0) return [];
    for (const relationship of relationships) requireScope(relationship.tenantId, relationship.containerTags);

    const now = new Date();
    const values = relationships.map(r => ({
      ...(r.id ? { id: r.id } : {}),
      fromId: r.fromId,
      toId: r.toId,
      type: r.type || 'extends',
      confidence: r.confidence ?? 1.0,
      reasoning: r.reasoning,
      createdAt: r.createdAt ? new Date(r.createdAt) : now,
    }));

    const result = await this.db.transaction(async tx => {
      const ids = [...new Set(values.flatMap(value => [value.fromId, value.toId]))].sort((a, b) => a < b ? -1 : a > b ? 1 : 0);
      const rows = await tx.select().from(memories).where(and(inArray(memories.id, ids), isNull(memories.deletedAt))).orderBy(memories.id).for('update');
      const byId = new Map(rows.map(row => [row.id, row]));
      for (const [index, value] of values.entries()) {
        const from = byId.get(value.fromId); const to = byId.get(value.toId);
        const scope = relationships[index];
        const inScope = (memory: typeof from) => memory
          && memory.tenantId === scope.tenantId
          && scope.containerTags.every(tag => memory.containerTags.includes(tag));
        if (!inScope(from) || !inScope(to)) throw new Error('MEMORY_RELATION_SCOPE_INVALID');
      }
      return tx.insert(memoryRelationships).values(values).returning();
    }).catch(error => {
      const cause = error?.cause ?? error;
      if (cause?.code === "23505") throw new Error("MEMORY_RELATION_EXISTS", { cause: error });
      throw error;
    });

    return result.map(r => ({
      id: r.id,
      fromId: r.fromId,
      toId: r.toId,
      type: r.type as any,
      confidence: r.confidence,
      reasoning: r.reasoning || undefined,
      createdAt: r.createdAt.getTime(),
    }));
  }

  async searchVectors(params: {
    tenantId: string;
    embedding: number[];
    containerTags: string[];
    filters?: Record<string, any>;
    topK: number;
    threshold?: number;
  }): Promise<Memory[]> {
    requireScope(params.tenantId, params.containerTags);
    const { tenantId, embedding, containerTags, topK, threshold } = params;

    // pgvector cosine similarity operator is <=>
    // We want to sort by distance ascending (closest first)
    // distance = 1 - similarity
    // To filter by threshold (similarity), distance should be <= (1 - threshold)
    
    const similarity = sql<number>`1 - (${memories.embedding} <=> ${JSON.stringify(embedding)}::vector)`;
    
    let query = this.db.select({
      memory: memories,
      similarity: similarity
    })
    .from(memories);

    // Build Where Clauses
    const conditions = [eq(memories.tenantId, tenantId), isNull(memories.deletedAt), eq(memories.isLatest, true)];

    // All supplied tags constrain retrieval within the explicit tenant.
    if (containerTags && containerTags.length > 0) {
      conditions.push(arrayContains(memories.containerTags, containerTags));
    }

    if (threshold !== undefined) {
        conditions.push(sql`(${memories.embedding} <=> ${JSON.stringify(embedding)}::vector) <= ${1 - threshold}`);
    }

    if (params.filters) {
        // Simple metadata exact match support
        for (const [key, value] of Object.entries(params.filters)) {
            // JSONB containment @>
            conditions.push(sql`${memories.metadata} @> ${JSON.stringify({ [key]: value })}`);
        }
    }

    if (conditions.length > 0) {
        query = query.where(and(...conditions)) as any;
    }

    const results = await query
        .orderBy(sql`${memories.embedding} <=> ${JSON.stringify(embedding)}::vector ASC`)
        .limit(topK);

    return results.map(r => this.mapToDomain(r.memory));
  }


  private scope(input: MemoryScope & { id: string }) {
    requireScope(input.tenantId, input.containerTags);
    return and(eq(memories.id, input.id), eq(memories.tenantId, input.tenantId),
      input.containerTags.length ? arrayContains(memories.containerTags, input.containerTags) : undefined);
  }

  async getMemory(input: MemoryScope & { id: string }): Promise<Memory | null> {
    const [row] = await this.db.select().from(memories).where(and(this.scope(input), isNull(memories.deletedAt))).limit(1);
    return row ? this.mapToDomain(row) : null;
  }

  async updateMemory(input: MemoryUpdate): Promise<Memory> {
    const [row] = await this.db.update(memories).set({
      content: input.changes.content, embedding: input.changes.embedding,
      ...(input.changes.metadata === undefined ? {} : { metadata: input.changes.metadata }),
      ...(input.changes.isLatest === undefined ? {} : { isLatest: input.changes.isLatest }),
      revision: sql`${memories.revision} + 1`, updatedAt: new Date(),
    }).where(and(this.scope(input), isNull(memories.deletedAt), eq(memories.revision, input.expectedRevision))).returning();
    if (!row) throw new Error('MEMORY_REVISION_CONFLICT');
    return this.mapToDomain(row);
  }

  async deleteMemory(input: MemoryDelete): Promise<void> {
    const scope = this.scope(input);
    await this.db.transaction(async tx => {
      const [current] = await tx.select().from(memories).where(scope).for('update');
      if (!current) throw new Error('MEMORY_NOT_FOUND');
      if (current.deletedAt != null) return;
      if (input.expectedRevision !== undefined && current.revision !== input.expectedRevision) throw new Error('MEMORY_REVISION_CONFLICT');
      await tx.update(memories).set({ content: '', embedding: null, metadata: {}, isLatest: false,
        deletedAt: new Date(), updatedAt: new Date(), revision: sql`${memories.revision} + 1` }).where(scope);
      await tx.delete(memoryRelationships).where(or(eq(memoryRelationships.fromId, input.id), eq(memoryRelationships.toId, input.id)));
    });
  }

  private mapToDomain(row: typeof memories.$inferSelect): Memory {
    return {
      id: row.id,
      tenantId: row.tenantId,
      containerTags: row.containerTags,
      type: row.type as any,
      content: row.content,
      embedding: row.embedding,
      metadata: row.metadata as Record<string, any>,
      isLatest: row.isLatest,
      revision: row.revision,
      deletedAt: row.deletedAt?.getTime() ?? null,
      createdAt: row.createdAt.getTime(),
      updatedAt: row.updatedAt.getTime(),
    };
  }
}
