// @ts-nocheck
// Generated by @datafn/cli. DO NOT EDIT.
// Database: postgres
import { bigint, boolean, index, jsonb, numeric, pgTable, primaryKey, text, uniqueIndex } from "drizzle-orm/pg-core";

export const categories = pgTable("categories", {
  __ns: text("__ns").notNull(),
  color: text("color").notNull().default("#646cff"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  createdBy: text("created_by"),
  id: text("id").notNull(),
  name: text("name").notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
  updatedBy: text("updated_by"),
}, (table) => [
  primaryKey({ columns: [table.__ns, table.id] }),
  index("idx_categories___ns").on(table.__ns),
  index("categories_name_idx").on(table.name),
]);

export const kv = pgTable("kv", {
  __ns: text("__ns").notNull(),
  id: text("id").notNull(),
  value: jsonb("value"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
  createdBy: text("created_by"),
  updatedBy: text("updated_by"),
}, (table) => [
  primaryKey({ columns: [table.__ns, table.id] }),
  index("idx_kv___ns").on(table.__ns),
]);

export const todos = pgTable("todos", {
  __ns: text("__ns").notNull(),
  completed: boolean("completed").notNull().default(false),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  createdBy: text("created_by"),
  id: text("id").notNull(),
  isArchived: boolean("is_archived").notNull().default(false),
  priority: numeric("priority").default(3),
  text: text("text").notNull(),
  trashedAt: bigint("trashed_at", { mode: "number" }),
  trashedBy: text("trashed_by"),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
  updatedBy: text("updated_by"),
}, (table) => [
  primaryKey({ columns: [table.__ns, table.id] }),
  index("idx_todos___ns").on(table.__ns),
  index("todos_completed_idx").on(table.completed),
]);

export const __datafn_join_todos_tags = pgTable("__datafn_join_todos_tags", {
  __ns: text("__ns").notNull(),
  createdAt: bigint("created_at", { mode: "number" }),
  createdBy: text("created_by"),
  from: text("from").notNull(),
  id: text("id").notNull(),
  to: text("to").notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }),
  updatedBy: text("updated_by"),
}, (table) => [
  primaryKey({ columns: [table.__ns, table.id] }),
  index("idx___datafn_join_todos_tags___ns").on(table.__ns),
  uniqueIndex("__datafn_join_todos_tags_from_to_idx").on(table.from, table.to),
]);

export const schema = { __datafn_join_todos_tags, categories, kv, todos };
