// Generated by @datafn/cli. DO NOT EDIT.
// Database: sqlite
import { index, integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const documents = sqliteTable("documents", {
  __ns: text("__ns").notNull(),
  content: text("content").notNull(),
  createdAt: integer("created_at").notNull(),
  createdBy: text("created_by"),
  id: text("id").notNull(),
  title: text("title").notNull(),
  updatedAt: integer("updated_at").notNull(),
  updatedBy: text("updated_by"),
  visibility: text("visibility"),
}, (table) => [
  primaryKey({ columns: [table.__ns, table.id] }),
  index("idx_documents___ns").on(table.__ns),
  index("documents_title_idx").on(table.title),
  index("idx_documents_visibility").on(table.visibility),
  index("idx_documents_created_by_visibility").on(table.createdBy, table.visibility),
]);

export const kv = sqliteTable("kv", {
  __ns: text("__ns").notNull(),
  id: text("id").notNull(),
  value: text("value"),
}, (table) => [
  primaryKey({ columns: [table.__ns, table.id] }),
  index("idx_kv___ns").on(table.__ns),
]);

export const __datafn_permissions_global = sqliteTable("__datafn_permissions_global", {
  __ns: text("__ns"),
  id: text("id").notNull(),
  resourceType: text("resource_type").notNull(),
  resourceNs: text("resource_ns").notNull(),
  resourceId: text("resource_id"),
  principalId: text("principal_id").notNull(),
  level: text("level").notNull(),
  grantKind: text("grant_kind").notNull(),
  sourceRef: text("source_ref"),
  grantedBy: text("granted_by").notNull(),
  grantedAt: integer("granted_at").notNull(),
  revokedAt: integer("revoked_at"),
}, (table) => [
  primaryKey({ columns: [table.id] }),
  uniqueIndex("__datafn_permissions_global_resource_record_idx").on(table.resourceType, table.resourceNs, table.resourceId, table.principalId),
  uniqueIndex("__datafn_permissions_global_scope_idx").on(table.resourceType, table.resourceNs, table.principalId, table.grantKind),
  index("idx_perm_principal").on(table.principalId),
  index("idx_perm_resource_ns_principal").on(table.resourceNs, table.principalId),
  index("idx_perm_resource_lookup").on(table.resourceType, table.resourceNs, table.resourceId),
  index("idx_perm_active_lookup").on(table.resourceType, table.resourceNs, table.principalId, table.revokedAt),
]);

export const __datafn_principal_memberships = sqliteTable("__datafn_principal_memberships", {
  __ns: text("__ns"),
  id: text("id").notNull(),
  namespace: text("namespace").notNull(),
  actorId: text("actor_id").notNull(),
  principalId: text("principal_id").notNull(),
  grantedAt: integer("granted_at").notNull(),
  revokedAt: integer("revoked_at"),
}, (table) => [
  primaryKey({ columns: [table.id] }),
  uniqueIndex("__datafn_principal_memberships_namespace_actor_principal_idx").on(table.namespace, table.actorId, table.principalId),
  index("idx_membership_actor").on(table.namespace, table.actorId),
  index("idx_membership_principal").on(table.namespace, table.principalId),
  index("idx_membership_active").on(table.namespace, table.actorId, table.revokedAt),
]);

export const __datafn_principal_hierarchy = sqliteTable("__datafn_principal_hierarchy", {
  __ns: text("__ns"),
  id: text("id").notNull(),
  namespace: text("namespace").notNull(),
  principalId: text("principal_id").notNull(),
  parentPrincipalId: text("parent_principal_id").notNull(),
  createdAt: integer("created_at").notNull(),
  revokedAt: integer("revoked_at"),
}, (table) => [
  primaryKey({ columns: [table.id] }),
  uniqueIndex("__datafn_principal_hierarchy_namespace_principal_parent_idx").on(table.namespace, table.principalId, table.parentPrincipalId),
  index("idx_hierarchy_principal").on(table.namespace, table.principalId),
  index("idx_hierarchy_parent").on(table.namespace, table.parentPrincipalId),
  index("idx_hierarchy_active").on(table.namespace, table.principalId, table.revokedAt),
]);

export const schema = { __datafn_permissions_global, __datafn_principal_hierarchy, __datafn_principal_memberships, documents, kv };
