import {
  type DatafnSchema,
  type DatafnFieldSchema,
  type DatafnRelationSchema,
  validateSchema,
  unwrapEnvelope,
  ensureBuiltinKv,
  isNamespaced,
  resolveCapabilities,
  getCapabilityFields,
  RELATION_CAPABILITY_FIELD_DEFS,
} from "@datafn/core";

export type Dialect = "postgres" | "mysql" | "sqlite";

/**
 * Generate Drizzle ORM schema from a DataFn schema.
 */
export function generateDrizzleSchema(
  schemaInput: unknown,
  dialect: Dialect,
): string {
  const schema = ensureBuiltinKv(unwrapEnvelope(validateSchema(schemaInput)));
  const lines: string[] = [];
  const usedImports = new Set<string>();
  const tableConstructor = getTableConstructor(dialect);
  const importPath = getImportPath(dialect);

  const tableExports: string[] = [];

  lines.push("// @ts-nocheck");
  lines.push("// Generated by @datafn/cli. DO NOT EDIT.");
  lines.push(`// Database: ${dialect}`);
  lines.push("");

  const resources = [...schema.resources].sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  const shareableResources: string[] = [];

  const nsEnabled = isNamespaced(schema);

  for (const resource of resources) {
    const tableName = resource.name;
    const varName = sanitizeVarName(tableName);
    tableExports.push(varName);
    usedImports.add(tableConstructor);

    const fields = ensureIdField(resource.fields).sort((a, b) =>
      a.name.localeCompare(b.name),
    );
    const resolvedCapabilities = resolveCapabilities(
      schema.capabilities,
      resource.capabilities,
    );
    const hasShareable = resolvedCapabilities.some(
      (capability) =>
        typeof capability === "object" &&
        capability !== null &&
        "shareable" in capability,
    );
    if (hasShareable) {
      shareableResources.push(resource.name);
    }

    const resolvedCapabilityFields = getCapabilityFields(resolvedCapabilities);
    const capabilityFieldNames = new Set(
      resolvedCapabilityFields.map((field) => field.name),
    );
    const capabilityFields = resolvedCapabilityFields.filter(
      (field) => !fields.some((userField) => userField.name === field.name),
    );
    if (hasShareable) {
      // Compatibility fallback: older core builds may not inject `visibility` yet.
      capabilityFieldNames.add("visibility");
      if (!fields.some((field) => field.name === "visibility")) {
        capabilityFields.push({
          name: "visibility",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
          default: null,
        });
      }
    }

    const hasBaseIndices =
      resource.indices &&
      typeof resource.indices === "object" &&
      !Array.isArray(resource.indices) &&
      resource.indices.base?.length;
    const hasExplicitIdField = fields.some((field) => field.name === "id");

    lines.push(`export const ${varName} = ${tableConstructor}("${tableName}", {`);

    // Add __ns column when namespaced (alphabetical: __ns sorts before all alpha fields)
    if (nsEnabled) {
      usedImports.add("text");
      lines.push(`  __ns: text("__ns").notNull(),`);
    }

    for (const field of fields) {
      const colDef = capabilityFieldNames.has(field.name)
        ? buildCapabilityColumnDefinition(field, dialect, usedImports)
        : buildColumnDefinition(field, dialect, usedImports, nsEnabled);
      lines.push(`  ${renderTsObjectKey(field.name)}: ${colDef},`);
    }
    for (const field of capabilityFields) {
      const colDef = buildCapabilityColumnDefinition(field, dialect, usedImports);
      lines.push(`  ${renderTsObjectKey(field.name)}: ${colDef},`);
    }

    const needsIndexCallback = hasBaseIndices || nsEnabled || hasShareable;

    if (needsIndexCallback) {
      usedImports.add("index");
      lines.push(`}, (table) => [`);
      if (nsEnabled) {
        if (hasExplicitIdField) {
          usedImports.add("primaryKey");
          lines.push(`  primaryKey({ columns: [table.__ns, ${tableAccessor("id")}] }),`);
        }
        lines.push(`  index("idx_${tableName}___ns").on(table.__ns),`);
      }
      if (hasBaseIndices) {
        const baseIndices = (resource.indices as { base?: string[] }).base!;
        for (const idxField of baseIndices) {
          lines.push(
            `  index("${tableName}_${camelToSnake(idxField)}_idx").on(${tableAccessor(idxField)}),`,
          );
        }
      }
      if (hasShareable) {
        // PERF-001: optimize private/shared query paths.
        lines.push(`  index("idx_${tableName}_visibility").on(${tableAccessor("visibility")}),`);
        lines.push(
          `  index("idx_${tableName}_created_by_visibility").on(${tableAccessor("createdBy")}, ${tableAccessor("visibility")}),`,
        );
      }
      lines.push(`]);`);
    } else {
      lines.push(`});`);
    }
    lines.push("");
  }

  if (shareableResources.length > 0) {
    const permissionsTableName = "__datafn_permissions_global";
    const membershipsTableName = "__datafn_principal_memberships";
    const hierarchyTableName = "__datafn_principal_hierarchy";

    const permissionsVarName = sanitizeVarName(permissionsTableName);
    const membershipsVarName = sanitizeVarName(membershipsTableName);
    const hierarchyVarName = sanitizeVarName(hierarchyTableName);

    tableExports.push(permissionsVarName, membershipsVarName, hierarchyVarName);

    usedImports.add(tableConstructor);
    usedImports.add("text");
    usedImports.add("primaryKey");
    usedImports.add("uniqueIndex");
    usedImports.add("index");

    // SQLite has no bigint — use integer instead
    const tsCol = dialect === "sqlite"
      ? (name: string) => { usedImports.add("integer"); return `integer("${name}")`; }
      : (name: string) => { usedImports.add("bigint"); return `bigint("${name}", { mode: "number" })`; };

    lines.push(
      `export const ${permissionsVarName} = ${tableConstructor}("${permissionsTableName}", {`,
    );
    if (nsEnabled) {
      lines.push(`  __ns: text("__ns"),`);
    }
    lines.push(`  id: text("id").notNull(),`);
    lines.push(`  resourceType: text("resource_type").notNull(),`);
    lines.push(`  resourceNs: text("resource_ns").notNull(),`);
    lines.push(`  resourceId: text("resource_id"),`);
    lines.push(`  principalId: text("principal_id").notNull(),`);
    lines.push(`  level: text("level").notNull(),`);
    lines.push(`  grantKind: text("grant_kind").notNull(),`);
    lines.push(`  sourceRef: text("source_ref"),`);
    lines.push(`  grantedBy: text("granted_by").notNull(),`);
    lines.push(`  grantedAt: ${tsCol("granted_at")}.notNull(),`);
    lines.push(`  revokedAt: ${tsCol("revoked_at")},`);
    lines.push(`}, (table) => [`);
    lines.push(`  primaryKey({ columns: [table.id] }),`);
    lines.push(
      `  uniqueIndex("${permissionsTableName}_resource_record_idx").on(table.resourceType, table.resourceNs, table.resourceId, table.principalId),`,
    );
    lines.push(
      `  uniqueIndex("${permissionsTableName}_scope_idx").on(table.resourceType, table.resourceNs, table.principalId, table.grantKind),`,
    );
    lines.push(`  index("idx_perm_principal").on(table.principalId),`);
    lines.push(
      `  index("idx_perm_resource_ns_principal").on(table.resourceNs, table.principalId),`,
    );
    lines.push(
      `  index("idx_perm_resource_lookup").on(table.resourceType, table.resourceNs, table.resourceId),`,
    );
    lines.push(
      `  index("idx_perm_active_lookup").on(table.resourceType, table.resourceNs, table.principalId, table.revokedAt),`,
    );
    lines.push(`]);`);
    lines.push("");

    lines.push(
      `export const ${membershipsVarName} = ${tableConstructor}("${membershipsTableName}", {`,
    );
    if (nsEnabled) {
      lines.push(`  __ns: text("__ns"),`);
    }
    lines.push(`  id: text("id").notNull(),`);
    lines.push(`  namespace: text("namespace").notNull(),`);
    lines.push(`  actorId: text("actor_id").notNull(),`);
    lines.push(`  principalId: text("principal_id").notNull(),`);
    lines.push(`  grantedAt: ${tsCol("granted_at")}.notNull(),`);
    lines.push(`  revokedAt: ${tsCol("revoked_at")},`);
    lines.push(`}, (table) => [`);
    lines.push(`  primaryKey({ columns: [table.id] }),`);
    lines.push(
      `  uniqueIndex("${membershipsTableName}_namespace_actor_principal_idx").on(table.namespace, table.actorId, table.principalId),`,
    );
    lines.push(`  index("idx_membership_actor").on(table.namespace, table.actorId),`);
    lines.push(
      `  index("idx_membership_principal").on(table.namespace, table.principalId),`,
    );
    lines.push(
      `  index("idx_membership_active").on(table.namespace, table.actorId, table.revokedAt),`,
    );
    lines.push(`]);`);
    lines.push("");

    lines.push(
      `export const ${hierarchyVarName} = ${tableConstructor}("${hierarchyTableName}", {`,
    );
    if (nsEnabled) {
      lines.push(`  __ns: text("__ns"),`);
    }
    lines.push(`  id: text("id").notNull(),`);
    lines.push(`  namespace: text("namespace").notNull(),`);
    lines.push(`  principalId: text("principal_id").notNull(),`);
    lines.push(`  parentPrincipalId: text("parent_principal_id").notNull(),`);
    lines.push(`  createdAt: ${tsCol("created_at")}.notNull(),`);
    lines.push(`  revokedAt: ${tsCol("revoked_at")},`);
    lines.push(`}, (table) => [`);
    lines.push(`  primaryKey({ columns: [table.id] }),`);
    lines.push(
      `  uniqueIndex("${hierarchyTableName}_namespace_principal_parent_idx").on(table.namespace, table.principalId, table.parentPrincipalId),`,
    );
    lines.push(
      `  index("idx_hierarchy_principal").on(table.namespace, table.principalId),`,
    );
    lines.push(
      `  index("idx_hierarchy_parent").on(table.namespace, table.parentPrincipalId),`,
    );
    lines.push(
      `  index("idx_hierarchy_active").on(table.namespace, table.principalId, table.revokedAt),`,
    );
    lines.push(`]);`);
    lines.push("");
  }

  emitInternalTables(lines, tableExports, usedImports, tableConstructor, dialect);

  const relations = schema.relations ?? [];
  const sortedRelations = [...relations]
    .filter((rel) => rel.type === "many-many")
    .sort((a, b) => {
      const aName = getJoinTableName(a);
      const bName = getJoinTableName(b);
      return aName.localeCompare(bName);
    });

  for (const rel of sortedRelations) {
    const jtName = getJoinTableName(rel);
    const varName = sanitizeVarName(jtName);
    tableExports.push(varName);
    usedImports.add(tableConstructor);

    const fromCol = rel.joinColumns?.from ?? "from";
    const toCol = rel.joinColumns?.to ?? "to";

    lines.push(`export const ${varName} = ${tableConstructor}("${jtName}", {`);

    const joinFields: Array<{ name: string; def: string }> = [];

    // Add __ns column for join tables when namespaced
    if (nsEnabled) {
      usedImports.add("text");
      joinFields.push({
        name: "__ns",
        def: `text("__ns").notNull()`,
      });
    }

    joinFields.push(
      {
        name: fromCol,
        def: buildSimpleColumn(fromCol, "string", dialect, usedImports, true),
      },
      {
        name: "id",
        def: buildSimpleColumn(
          "id",
          "string",
          dialect,
          usedImports,
          nsEnabled, // notNull when namespaced (PK defined in callback)
          !nsEnabled, // primaryKey only when not namespaced
        ),
      },
      {
        name: toCol,
        def: buildSimpleColumn(toCol, "string", dialect, usedImports, true),
      },
    );

    if (rel.metadata) {
      for (const meta of rel.metadata) {
        joinFields.push({
          name: meta.name,
          def: buildSimpleColumn(
            meta.name,
            meta.type,
            dialect,
            usedImports,
            false,
          ),
        });
      }
    }

    // JCG-001: Inject relation capability columns for opted-in many-many relations
    if (rel.capabilities && rel.capabilities.length > 0) {
      const canonicalCaps = (["timestamps", "audit"] as const).filter(
        (cap) => (rel.capabilities as string[]).includes(cap),
      );
      for (const cap of canonicalCaps) {
        for (const fieldDef of RELATION_CAPABILITY_FIELD_DEFS[cap]) {
          const snakeName = camelToSnake(fieldDef.name);
          const { call, importName } = fieldDef.type === "date"
            ? getEpochColumnType(dialect, snakeName)
            : getColumnType(fieldDef.type, dialect, snakeName);
          usedImports.add(importName);
          joinFields.push({
            name: fieldDef.name,
            def: call,
          });
        }
      }
    }

    joinFields.sort((a, b) => a.name.localeCompare(b.name));

    for (const jf of joinFields) {
      lines.push(`  ${renderTsObjectKey(jf.name)}: ${jf.def},`);
    }

    const fromSnake = camelToSnake(fromCol);
    const toSnake = camelToSnake(toCol);
    usedImports.add("uniqueIndex");
    lines.push(`}, (table) => [`);
    if (nsEnabled) {
      usedImports.add("index");
      usedImports.add("primaryKey");
      lines.push(`  primaryKey({ columns: [table.__ns, table.id] }),`);
      lines.push(`  index("idx_${jtName}___ns").on(table.__ns),`);
    }
    const uniqueColumns = nsEnabled
      ? `table.__ns, ${tableAccessor(fromCol)}, ${tableAccessor(toCol)}`
      : `${tableAccessor(fromCol)}, ${tableAccessor(toCol)}`;
    lines.push(`  uniqueIndex("${jtName}_${fromSnake}_${toSnake}_idx").on(${uniqueColumns}),`);
    lines.push(`]);`);
    lines.push("");
  }

  tableExports.sort();
  lines.push(`export const schema = { ${tableExports.join(", ")} };`);
  lines.push("");

  const sortedImports = [...usedImports].sort();
  const importLine = `import { ${sortedImports.join(", ")} } from "${importPath}";`;

  lines.splice(2, 0, importLine);

  return lines.join("\n");
}

function getTableConstructor(dialect: Dialect): string {
  switch (dialect) {
    case "postgres":
      return "pgTable";
    case "mysql":
      return "mysqlTable";
    case "sqlite":
      return "sqliteTable";
  }
}

function getImportPath(dialect: Dialect): string {
  switch (dialect) {
    case "postgres":
      return "drizzle-orm/pg-core";
    case "mysql":
      return "drizzle-orm/mysql-core";
    case "sqlite":
      return "drizzle-orm/sqlite-core";
  }
}

export function camelToSnake(str: string): string {
  return str
    .replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function sanitizeVarName(name: string): string {
  const sanitized = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(sanitized) ? sanitized : `_${sanitized}`;
}

function buildColumnDefinition(
  field: DatafnFieldSchema,
  dialect: Dialect,
  usedImports: Set<string>,
  isNamespaced = false,
): string {
  const snakeName = camelToSnake(field.name);
  const { call, importName } = field.type === "date"
    ? getEpochColumnType(dialect, snakeName)
    : getColumnType(field.type, dialect, snakeName);
  usedImports.add(importName);

  let def = call;

  if (field.name === "id") {
    // In namespaced mode, composite PK (__ns, id) is defined in the table callback
    if (!isNamespaced) {
      def += ".primaryKey()";
    } else {
      def += ".notNull()";
    }
  } else {
    if (field.required) def += ".notNull()";
    if (field.unique === true) def += ".unique()";
  }

  if (field.default !== undefined) {
    def += `.default(${JSON.stringify(field.default)})`;
  }

  return def;
}

function renderTsObjectKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function ensureIdField(fields: DatafnFieldSchema[]): DatafnFieldSchema[] {
  if (fields.some((field) => field.name === "id")) {
    return [...fields];
  }

  return [
    { name: "id", type: "string", required: true, readonly: true },
    ...fields,
  ];
}

function tableAccessor(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? `table.${name}`
    : `table[${JSON.stringify(name)}]`;
}

function buildSimpleColumn(
  fieldName: string,
  fieldType: string,
  dialect: Dialect,
  usedImports: Set<string>,
  notNull: boolean,
  primaryKey = false,
): string {
  const snakeName = camelToSnake(fieldName);
  const { call, importName } = getColumnType(fieldType, dialect, snakeName);
  usedImports.add(importName);

  let def = call;

  if (primaryKey) {
    def += ".primaryKey()";
  } else if (notNull) {
    def += ".notNull()";
  }

  return def;
}

function buildCapabilityColumnDefinition(
  field: DatafnFieldSchema,
  dialect: Dialect,
  usedImports: Set<string>,
): string {
  const snakeName = camelToSnake(field.name);
  const { call, importName } = getColumnType(field.type, dialect, snakeName);
  usedImports.add(importName);

  let def = call;

  if (field.name === "createdAt" || field.name === "updatedAt") {
    def += ".notNull()";
  } else if (field.name === "isArchived") {
    def += ".notNull().default(false)";
  }

  return def;
}

function emitInternalTables(
  lines: string[],
  tableExports: string[],
  usedImports: Set<string>,
  tableConstructor: string,
  dialect: Dialect,
): void {
  const tables = [
    {
      tableName: "__datafn_changes",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "server_seq", sqlName: "server_seq", type: "integer" },
        { property: "resource", sqlName: "resource", type: "text" },
        { property: "record_id", sqlName: "record_id", type: "text" },
        { property: "op", sqlName: "op", type: "text" },
        { property: "record", sqlName: "record", type: "text" },
        { property: "created_at", sqlName: "created_at", type: "text" },
      ],
      indexes: [
        'index("__datafn_changes_namespace_server_seq_idx").on(table.namespace, table.server_seq)',
      ],
    },
    {
      tableName: "__datafn_idempotency",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "client_id", sqlName: "client_id", type: "text" },
        { property: "mutation_id", sqlName: "mutation_id", type: "text" },
        { property: "result", sqlName: "result", type: "text" },
        { property: "created_at", sqlName: "created_at", type: "text" },
      ],
      indexes: [
        'index("__datafn_idempotency_namespace_client_mutation_idx").on(table.namespace, table.client_id, table.mutation_id)',
      ],
    },
    {
      tableName: "__datafn_meta",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "next_server_seq", sqlName: "next_server_seq", type: "integer" },
      ],
      indexes: [] as string[],
    },
    {
      tableName: "__datafn_seed",
      columns: [
        { property: "id", sqlName: "id", type: "text", primaryKey: true },
        { property: "namespace", sqlName: "namespace", type: "text" },
        { property: "seed_id", sqlName: "seed_id", type: "text" },
        { property: "status", sqlName: "status", type: "text" },
        { property: "created_at", sqlName: "created_at", type: "text" },
      ],
      indexes: [
        'index("__datafn_seed_namespace_seed_idx").on(table.namespace, table.seed_id)',
      ],
    },
  ];

  usedImports.add(tableConstructor);
  usedImports.add("text");

  for (const table of tables) {
    const varName = sanitizeVarName(table.tableName);
    tableExports.push(varName);

    lines.push(`export const ${varName} = ${tableConstructor}("${table.tableName}", {`);
    for (const column of table.columns) {
      let def: string;
      if (column.type === "integer") {
        const { call, importName } = getInternalIntegerColumnType(dialect, column.sqlName);
        usedImports.add(importName);
        def = call;
      } else {
        def = `text("${column.sqlName}")`;
      }
      if (column.primaryKey) {
        def += ".primaryKey()";
      }
      lines.push(`  ${column.property}: ${def},`);
    }

    if (table.indexes.length > 0) {
      usedImports.add("index");
      lines.push(`}, (table) => [`);
      for (const indexDef of table.indexes) {
        lines.push(`  ${indexDef},`);
      }
      lines.push(`]);`);
    } else {
      lines.push(`});`);
    }
    lines.push("");
  }
}

function getColumnType(
  fieldType: string,
  dialect: Dialect,
  sqlName: string,
): { call: string; importName: string } {
  if (dialect === "postgres") {
    switch (fieldType) {
      case "string":
      case "file":
        return { call: `text("${sqlName}")`, importName: "text" };
      case "number":
        return { call: `numeric("${sqlName}")`, importName: "numeric" };
      case "boolean":
        return { call: `boolean("${sqlName}")`, importName: "boolean" };
      case "date":
        return getEpochColumnType(dialect, sqlName);
      case "object":
      case "array":
      case "json":
        return { call: `jsonb("${sqlName}")`, importName: "jsonb" };
      default:
        return { call: `text("${sqlName}")`, importName: "text" };
    }
  }

  if (dialect === "mysql") {
    switch (fieldType) {
      case "string":
      case "file":
        return { call: `text("${sqlName}")`, importName: "text" };
      case "number":
        return { call: `int("${sqlName}")`, importName: "int" };
      case "boolean":
        return { call: `boolean("${sqlName}")`, importName: "boolean" };
      case "date":
        return {
          call: `bigint("${sqlName}", { mode: "number" })`,
          importName: "bigint",
        };
      case "object":
      case "array":
      case "json":
        return { call: `json("${sqlName}")`, importName: "json" };
      default:
        return { call: `text("${sqlName}")`, importName: "text" };
    }
  }

  switch (fieldType) {
    case "string":
    case "file":
    case "object":
    case "array":
    case "json":
      return { call: `text("${sqlName}")`, importName: "text" };
    case "number":
    case "boolean":
    case "date":
      return { call: `integer("${sqlName}")`, importName: "integer" };
    default:
      return { call: `text("${sqlName}")`, importName: "text" };
  }
}

function getInternalIntegerColumnType(
  dialect: Dialect,
  sqlName: string,
): { call: string; importName: string } {
  if (dialect === "mysql") {
    return { call: `int("${sqlName}")`, importName: "int" };
  }
  return { call: `integer("${sqlName}")`, importName: "integer" };
}

function getEpochColumnType(
  dialect: Dialect,
  sqlName: string,
): { call: string; importName: string } {
  if (dialect === "sqlite") {
    return { call: `integer("${sqlName}")`, importName: "integer" };
  }
  return { call: `bigint("${sqlName}", { mode: "number" })`, importName: "bigint" };
}

function getJoinTableName(rel: DatafnRelationSchema): string {
  if (rel.joinTable) return rel.joinTable;

  const from = Array.isArray(rel.from) ? rel.from[0] : rel.from;
  const relation = rel.relation ?? (Array.isArray(rel.to) ? rel.to[0] : rel.to);
  return `__datafn_join_${from}_${relation}`;
}
