// Generated by @datafn/cli. DO NOT EDIT.
// Database: postgres
import { boolean, pgTable, text } from "drizzle-orm/pg-core";

export const todos = pgTable("todos", {
  completed: boolean("completed").default(false),
  id: text("id").primaryKey(),
  text: text("text").notNull(),
});

export const schema = { todos };
