"""Python contract surface for the multi-package authfn platform."""

__version__ = "0.0.1"
__author__ = "21n"
__license__ = "MIT"

from .authfn import AuthFn, AuthFnProvider, create_authfn
from .config import get_plugin, get_plugin_config, normalize_config, resolve_runtime
from .http import create_authfn_openapi, create_authfn_routes
from .plugins.api_keys import ApiKeyPluginConfig, ApiKeyService
from .plugins.email_otp import EmailOtpPluginConfig, EmailOtpService
from .plugins.social_oauth import (
    SocialOAuthPluginConfig,
    SocialOAuthService,
    SocialProviderConfig,
)
from .plugins.two_factor import TwoFactorPluginConfig, TwoFactorService
from .plugins.multi_region import (
    MultiRegionPluginConfig,
    MultiRegionRegionConfig,
    MultiRegionService,
)
from .schema import AUTHFN_SCHEMA_VERSION, get_schema
from .types import (
    ApiKey,
    ApiKeyCreate,
    ApiKeyResponse,
    ApiKeySanitized,
    ApiKeySession,
    ApiKeyRevokedError,
    AuthFnConfig,
    AuthFnCookieConfig,
    AuthFnError,
    AuthFnEvent,
    AuthFnHookContext,
    AuthFnHooks,
    AuthFnObservabilityConfig,
    AuthFnPlugin,
    AuthFnPluginRuntimeContext,
    AuthFnRuntimeResolution,
    AuthFnRuntimeResolver,
    AuthFnSchemaConflictError,
    AuthFnSession,
    ConfigError,
    ConflictError,
    CsrfInvalidError,
    DeliveryFailedError,
    EmailNotVerifiedError,
    ExpiredCredentialsError,
    InternalError,
    InvalidCredentialsError,
    NotFoundError,
    NotImplementedAuthError,
    OtpExpiredError,
    OtpInvalidError,
    OtpReplayedError,
    OAuthCallbackInvalidError,
    OAuthProviderUnsupportedError,
    OAuthStateInvalidError,
    OAuthStateReplayedError,
    PluginAbortedError,
    RateLimitedError,
    RedirectUriDisallowedError,
    RegionMismatchError,
    RegionNotFoundError,
    SessionExpiredError,
    SessionRevokedError,
    TwoFactorInvalidCodeError,
    TwoFactorRequiredError,
    UnauthorizedError,
    ValidationError,
    authfn_api_key_plugin,
    authfn_email_otp_plugin,
    authfn_multi_region_plugin,
    authfn_password_plugin,
    authfn_social_oauth_plugin,
    authfn_two_factor_plugin,
)

__all__ = [
    "__version__",
    "__author__",
    "__license__",
    "AUTHFN_SCHEMA_VERSION",
    "AuthFn",
    "AuthFnProvider",
    "create_authfn",
    "create_authfn_openapi",
    "create_authfn_routes",
    "ApiKeyPluginConfig",
    "ApiKeyService",
    "EmailOtpPluginConfig",
    "EmailOtpService",
    "SocialOAuthPluginConfig",
    "SocialOAuthService",
    "SocialProviderConfig",
    "TwoFactorPluginConfig",
    "TwoFactorService",
    "MultiRegionPluginConfig",
    "MultiRegionRegionConfig",
    "MultiRegionService",
    "AuthFnConfig",
    "AuthFnCookieConfig",
    "AuthFnEvent",
    "AuthFnObservabilityConfig",
    "AuthFnRuntimeResolution",
    "AuthFnRuntimeResolver",
    "normalize_config",
    "resolve_runtime",
    "get_plugin",
    "get_plugin_config",
    "AuthFnHookContext",
    "AuthFnHooks",
    "AuthFnPlugin",
    "AuthFnPluginRuntimeContext",
    "ApiKey",
    "ApiKeyCreate",
    "ApiKeyResponse",
    "ApiKeySanitized",
    "ApiKeySession",
    "AuthFnSession",
    "AuthFnError",
    "AuthFnSchemaConflictError",
    "ApiKeyRevokedError",
    "ConfigError",
    "ConflictError",
    "CsrfInvalidError",
    "ValidationError",
    "InvalidCredentialsError",
    "ExpiredCredentialsError",
    "InternalError",
    "DeliveryFailedError",
    "EmailNotVerifiedError",
    "OtpInvalidError",
    "OtpExpiredError",
    "OtpReplayedError",
    "OAuthCallbackInvalidError",
    "OAuthProviderUnsupportedError",
    "OAuthStateInvalidError",
    "OAuthStateReplayedError",
    "PluginAbortedError",
    "RateLimitedError",
    "RedirectUriDisallowedError",
    "RegionMismatchError",
    "RegionNotFoundError",
    "SessionExpiredError",
    "SessionRevokedError",
    "TwoFactorRequiredError",
    "TwoFactorInvalidCodeError",
    "UnauthorizedError",
    "NotFoundError",
    "NotImplementedAuthError",
    "authfn_password_plugin",
    "authfn_email_otp_plugin",
    "authfn_social_oauth_plugin",
    "authfn_api_key_plugin",
    "authfn_two_factor_plugin",
    "authfn_multi_region_plugin",
    "get_schema",
]
