import { describe, expect, it } from "vitest";
import { generateDrizzleSchema } from "../drizzle-codegen.js";

describe("Drizzle Codegen Capabilities", () => {
  it("TV-CG-001 / TV-CG-003: injects capability columns using resolved capabilities", () => {
    const schema = {
      namespaced: false,
      capabilities: ["timestamps", "audit", "trash"],
      resources: [
        {
          name: "todos",
          version: 1,
          capabilities: ["archivable"],
          fields: [
            { name: "id", type: "string", required: true },
            { name: "text", type: "string", required: true },
          ],
        },
        {
          name: "logs",
          version: 1,
          capabilities: { exclude: ["trash"] },
          fields: [
            { name: "id", type: "string", required: true },
            { name: "message", type: "string", required: true },
          ],
        },
      ],
      relations: [],
    };

    const output = generateDrizzleSchema(schema, "postgres");

    expect(output).toMatchInlineSnapshot(`
      "// @ts-nocheck
      // Generated by @datafn/cli. DO NOT EDIT.
      import { bigint, boolean, index, integer, jsonb, pgTable, text } from "drizzle-orm/pg-core";
      // Database: postgres

      export const kv = pgTable("kv", {
        id: text("id").primaryKey(),
        value: jsonb("value"),
        createdAt: bigint("created_at", { mode: "number" }).notNull(),
        updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
        createdBy: text("created_by"),
        updatedBy: text("updated_by"),
        trashedAt: bigint("trashed_at", { mode: "number" }),
        trashedBy: text("trashed_by"),
      });

      export const logs = pgTable("logs", {
        createdAt: bigint("created_at", { mode: "number" }).notNull(),
        createdBy: text("created_by"),
        id: text("id").primaryKey(),
        message: text("message").notNull(),
        updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
        updatedBy: text("updated_by"),
      });

      export const todos = pgTable("todos", {
        createdAt: bigint("created_at", { mode: "number" }).notNull(),
        createdBy: text("created_by"),
        id: text("id").primaryKey(),
        isArchived: boolean("is_archived").notNull().default(false),
        text: text("text").notNull(),
        trashedAt: bigint("trashed_at", { mode: "number" }),
        trashedBy: text("trashed_by"),
        updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
        updatedBy: text("updated_by"),
      });

      export const __datafn_changes = pgTable("__datafn_changes", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        server_seq: integer("server_seq"),
        resource: text("resource"),
        record_id: text("record_id"),
        op: text("op"),
        record: text("record"),
        created_at: text("created_at"),
      }, (table) => [
        index("__datafn_changes_namespace_server_seq_idx").on(table.namespace, table.server_seq),
      ]);

      export const __datafn_idempotency = pgTable("__datafn_idempotency", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        client_id: text("client_id"),
        mutation_id: text("mutation_id"),
        result: text("result"),
        created_at: text("created_at"),
      }, (table) => [
        index("__datafn_idempotency_namespace_client_mutation_idx").on(table.namespace, table.client_id, table.mutation_id),
      ]);

      export const __datafn_meta = pgTable("__datafn_meta", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        next_server_seq: integer("next_server_seq"),
      });

      export const __datafn_seed = pgTable("__datafn_seed", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        seed_id: text("seed_id"),
        status: text("status"),
        created_at: text("created_at"),
      }, (table) => [
        index("__datafn_seed_namespace_seed_idx").on(table.namespace, table.seed_id),
      ]);

      export const schema = { __datafn_changes, __datafn_idempotency, __datafn_meta, __datafn_seed, kv, logs, todos };
      "
    `);
  });

  it("TV-CG-002: generates permissions table for shareable resources", () => {
    const schema = {
      namespaced: false,
      resources: [
        {
          name: "docs",
          version: 1,
          capabilities: [
            "audit",
            {
              shareable: {
                levels: ["viewer", "editor", "owner"],
                default: "private",
              },
            },
          ],
          fields: [
            { name: "id", type: "string", required: true },
            { name: "title", type: "string", required: true },
          ],
        },
      ],
      relations: [],
    };

    const output = generateDrizzleSchema(schema, "postgres");

    expect(output).toMatchInlineSnapshot(`
      "// @ts-nocheck
      // Generated by @datafn/cli. DO NOT EDIT.
      import { bigint, index, integer, jsonb, pgTable, primaryKey, text, uniqueIndex } from "drizzle-orm/pg-core";
      // Database: postgres

      export const docs = pgTable("docs", {
        createdBy: text("created_by"),
        id: text("id").primaryKey(),
        title: text("title").notNull(),
        updatedBy: text("updated_by"),
        visibility: text("visibility"),
      }, (table) => [
        index("idx_docs_visibility").on(table.visibility),
        index("idx_docs_created_by_visibility").on(table.createdBy, table.visibility),
      ]);

      export const kv = pgTable("kv", {
        id: text("id").primaryKey(),
        value: jsonb("value"),
      });

      export const __datafn_permissions_global = pgTable("__datafn_permissions_global", {
        id: text("id").notNull(),
        resourceType: text("resource_type").notNull(),
        resourceNs: text("resource_ns").notNull(),
        resourceId: text("resource_id"),
        principalId: text("principal_id").notNull(),
        level: text("level").notNull(),
        grantKind: text("grant_kind").notNull(),
        sourceRef: text("source_ref"),
        grantedBy: text("granted_by").notNull(),
        grantedAt: bigint("granted_at", { mode: "number" }).notNull(),
        revokedAt: bigint("revoked_at", { mode: "number" }),
      }, (table) => [
        primaryKey({ columns: [table.id] }),
        uniqueIndex("__datafn_permissions_global_resource_record_idx").on(table.resourceType, table.resourceNs, table.resourceId, table.principalId),
        uniqueIndex("__datafn_permissions_global_scope_idx").on(table.resourceType, table.resourceNs, table.principalId, table.grantKind),
        index("idx_perm_principal").on(table.principalId),
        index("idx_perm_resource_ns_principal").on(table.resourceNs, table.principalId),
        index("idx_perm_resource_lookup").on(table.resourceType, table.resourceNs, table.resourceId),
        index("idx_perm_active_lookup").on(table.resourceType, table.resourceNs, table.principalId, table.revokedAt),
      ]);

      export const __datafn_principal_memberships = pgTable("__datafn_principal_memberships", {
        id: text("id").notNull(),
        namespace: text("namespace").notNull(),
        actorId: text("actor_id").notNull(),
        principalId: text("principal_id").notNull(),
        grantedAt: bigint("granted_at", { mode: "number" }).notNull(),
        revokedAt: bigint("revoked_at", { mode: "number" }),
      }, (table) => [
        primaryKey({ columns: [table.id] }),
        uniqueIndex("__datafn_principal_memberships_namespace_actor_principal_idx").on(table.namespace, table.actorId, table.principalId),
        index("idx_membership_actor").on(table.namespace, table.actorId),
        index("idx_membership_principal").on(table.namespace, table.principalId),
        index("idx_membership_active").on(table.namespace, table.actorId, table.revokedAt),
      ]);

      export const __datafn_principal_hierarchy = pgTable("__datafn_principal_hierarchy", {
        id: text("id").notNull(),
        namespace: text("namespace").notNull(),
        principalId: text("principal_id").notNull(),
        parentPrincipalId: text("parent_principal_id").notNull(),
        createdAt: bigint("created_at", { mode: "number" }).notNull(),
        revokedAt: bigint("revoked_at", { mode: "number" }),
      }, (table) => [
        primaryKey({ columns: [table.id] }),
        uniqueIndex("__datafn_principal_hierarchy_namespace_principal_parent_idx").on(table.namespace, table.principalId, table.parentPrincipalId),
        index("idx_hierarchy_principal").on(table.namespace, table.principalId),
        index("idx_hierarchy_parent").on(table.namespace, table.parentPrincipalId),
        index("idx_hierarchy_active").on(table.namespace, table.principalId, table.revokedAt),
      ]);

      export const __datafn_changes = pgTable("__datafn_changes", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        server_seq: integer("server_seq"),
        resource: text("resource"),
        record_id: text("record_id"),
        op: text("op"),
        record: text("record"),
        created_at: text("created_at"),
      }, (table) => [
        index("__datafn_changes_namespace_server_seq_idx").on(table.namespace, table.server_seq),
      ]);

      export const __datafn_idempotency = pgTable("__datafn_idempotency", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        client_id: text("client_id"),
        mutation_id: text("mutation_id"),
        result: text("result"),
        created_at: text("created_at"),
      }, (table) => [
        index("__datafn_idempotency_namespace_client_mutation_idx").on(table.namespace, table.client_id, table.mutation_id),
      ]);

      export const __datafn_meta = pgTable("__datafn_meta", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        next_server_seq: integer("next_server_seq"),
      });

      export const __datafn_seed = pgTable("__datafn_seed", {
        id: text("id").primaryKey(),
        namespace: text("namespace"),
        seed_id: text("seed_id"),
        status: text("status"),
        created_at: text("created_at"),
      }, (table) => [
        index("__datafn_seed_namespace_seed_idx").on(table.namespace, table.seed_id),
      ]);

      export const schema = { __datafn_changes, __datafn_idempotency, __datafn_meta, __datafn_permissions_global, __datafn_principal_hierarchy, __datafn_principal_memberships, __datafn_seed, docs, kv };
      "
    `);
  });
});
