import { createCipheriv, createDecipheriv, randomBytes, createHash } from 'crypto';
import { verifyWebhookSignature } from '@superfunctions/webhooks';

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 16;
// const _AUTH_TAG_LENGTH = 16;
const KEY_LENGTH = 32;

export class EncryptionKeyError extends Error {
  readonly code = 'PLUGFN_ENCRYPTION_KEY_INVALID';

  constructor(message: string) {
    super(message);
    this.name = 'EncryptionKeyError';
  }
}

/**
 * Generate a random encryption key (hex encoded)
 */
export function generateEncryptionKey(): string {
  return randomBytes(KEY_LENGTH).toString('hex');
}

export function validateEncryptionKey(key: string): void {
  if (typeof key !== 'string' || key.length === 0) {
    throw new EncryptionKeyError('encryptionKey is required');
  }

  if (/^[a-f0-9]{64}$/i.test(key)) {
    return;
  }

  throw new EncryptionKeyError(
    'encryptionKey must be a 32-byte hex key generated by generateEncryptionKey()'
  );
}

/**
 * Derive a key from a validated hex key string
 */
function deriveKey(key: string): Buffer {
  validateEncryptionKey(key);
  return Buffer.from(key, 'hex');
}

/**
 * Encrypt data using AES-256-GCM
 */
export function encrypt(data: string, encryptionKey: string): string {
  const key = deriveKey(encryptionKey);
  const iv = randomBytes(IV_LENGTH);
  
  const cipher = createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(data, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  const authTag = cipher.getAuthTag();
  
  // Format: iv:authTag:encrypted
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
}

/**
 * Decrypt data using AES-256-GCM
 */
export function decrypt(encryptedData: string, encryptionKey: string): string {
  const key = deriveKey(encryptionKey);
  const [ivHex, authTagHex, encrypted] = encryptedData.split(':');
  
  if (!ivHex || !authTagHex || !encrypted) {
    throw new Error('Invalid encrypted data format');
  }
  
  const iv = Buffer.from(ivHex, 'hex');
  const authTag = Buffer.from(authTagHex, 'hex');
  
  const decipher = createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  
  let decrypted = decipher.update(encrypted, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  
  return decrypted;
}

/**
 * Hash a string using SHA-256
 */
export function hash(data: string): string {
  return createHash('sha256').update(data).digest('hex');
}

/**
 * Generate a random state parameter for OAuth
 */
export function generateState(): string {
  return randomBytes(32).toString('hex');
}

/**
 * Verify HMAC signature
 */
export function verifyHmacSignature(
  payload: string,
  signature: string,
  secret: string,
  algorithm: 'sha1' | 'sha256' = 'sha256'
): boolean {
  return verifyWebhookSignature(payload, signature, secret, {
    algorithm,
    encoding: 'hex',
  });
}
